# required parameters
samplesheet: '/path/to/samplesheet'
outputdir: '/path/to/output'

star_index: '/path/to/star/index'
ctat_lib: '/path/to/ctat_lib'
salmon_index: '/path/to/salmon_index'

pipeline_messaging_enabled: true
dispatcherURL: 'http://your/dispatcher/url'

# required parameters for azurebatch execution (-profile azurebatch)
workdir: 'az://path/to/workdir' # in blob storage account

active_directory_principal_id: ''
active_directory_principal_secret: ''
active_directory_tenant_id: ''

batch_location: ''
batch_account_name: ''
storage_account_name: ''

virtual_network: '/subscriptions/<value>/resourceGroups/<value>/providers/Microsoft.Network/virtualNetworks/<value>/subnets/<value>'

# docker.io registry credentials
registry_username: ''
registry_password: ''